language: go
go:
  - 1.5.1
env:
  - TRAVIS="yes"
install:
  - go get github.com/shadowsocks/shadowsocks-go/shadowsocks
  - go get github.com/cyfdecyf/color
script:
  - pushd $TRAVIS_BUILD_DIR
  - go test -v
  - ./script/test.sh
  - popd
